name: Pull request

on:
  pull_request:
    branches: [ main ]
    types:
      - opened # pull request is created
      - synchronize # commit(s) pushed to the pull request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python scripts/lint.py
